language: generic
sudo: required
services:
  - docker

after_success:
  - docker build -t complex-nginx ./nginx
  - docker build -t complex-client ./client-vite
  - docker build -t complex-server ./server
  - docker build -t complex-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD" docker.io
  - docker tag complex-nginx "$DOCKER_ID"/complex-nginx:complex-nginx
  - docker tag complex-client "$DOCKER_ID"/complex-client:complex-client
  - docker tag complex-server "$DOCKER_ID"/complex-server:complex-server
  - docker tag complex-worker "$DOCKER_ID"/complex-worker:complex-worker
  - docker push "$DOCKER_ID"/complex-worker:complex-worker
  - docker push "$DOCKER_ID"/complex-server:complex-server
  - docker push "$DOCKER_ID"/complex-nginx:complex-nginx
  - docker push "$DOCKER_ID"/complex-client:complex-client
